// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
var sumEvens = 0

function fib (max,x,y,sum){
  
  if(x % 2 === 0){
    sumEvens += x;
  }
  
  while(y < max){
    if(y % 2 ===0){
      sumEvens += y;
    }
    sum = y + x;
    x = y;
    y = sum;
  }
 console.log(sumEvens);
}
fib(4000000,1,2,0)